name: Codacy

on:
  push:
    branches:
      - master

jobs:
  codacy_coverage_reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@0.2.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: cobertura.xml
