name: Publish

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: prepare
        run: |
          npm install
          npm test
      - name: publish on npmjs
        run: npm publish --access public
        env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
